#!/bin/bash
# /etc/init.d/devicejs: starts DeviceJS & WigWag runtime

### BEGIN INIT INFO
# Provides:             devicejs
# Required-Start:       $remote_fs $time devicedbd
# Required-Stop:        $remote_fs $time
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        5
# Default-Stop:         0 1 6
# Short-Description:    System logger
### END INIT INFO
WIGWAGROOT="/wigwag"
RUNNER_DIR="${WIGWAGROOT}/devicejs-core-modules/Runner"
RUNNER_START_CMD="./start -c ./relay.config.json"
RUNNER_STOP_CMD="echo Need_Stop_Command"
export NODE_PATH=${WIGWAGROOT}/devicejs-core-modules/Runner/node_modules 



RUNNER_LOG="${WIGWAGROOT}/log/runner.log"

function congig_cpu_scaling() {
   MAX_FREQ=/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
   MIN_FREQ=/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
   cat $MAX_FREQ > $MIN_FREQ
   MAX_FREQ=/sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
   MIN_FREQ=/sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
   cat $MAX_FREQ > $MIN_FREQ
}

function temp_gpio_stuff() {
  echo 103 > /sys/class/gpio/export 
  echo 105 > /sys/class/gpio/export 
  echo out > /sys/class/gpio/gpio103/direction 
  echo out > /sys/class/gpio/gpio105/direction 
  echo 102 > /sys/class/gpio/export 
  echo out > /sys/class/gpio/gpio102/direction 
  echo 1 > /sys/class/gpio/gpio102/value
  echo 101 > /sys/class/gpio/export
  echo out > /sys/class/gpio/gpio101/direction
  echo 1 > /sys/class/gpio/gpio101/value
}

function stop_devjs() {
    pushd $RUNNER_DIR
    $RUNNER_STOP_CMD > $RUNNER_LOG 2>&1
    popd
}
function run_devjs() {

    temp_gpio_stuff

    if [ -e $RUNNER_LOG ]; then
	# some trivial log rotation
	mv $RUNNER_LOG $RUNNER_LOG.1
    fi
    
    ulimit -c unlimited
    pushd $RUNNER_DIR
    $RUNNER_START_CMD > $RUNNER_LOG 2>&1 &
    popd
}

case "$1" in
    start)
	eval $COLOR_BOLD
	echo "Starting DeviceJS services."
	eval $COLOR_NORMAL
        congig_cpu_scaling
	run_devjs
	;;
    stop)
	echo "Stopping DeviceJS"
        stop_devjs
        ;;
    restart) 
	echo "Restarting DeviceJS"
	stop_devjs
        congig_cpu_scaling
	run_devjs
  	;;
      *)
	echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0

     
