#! /bin/sh
# /etc/init.d/devicejs: starts DeviceJS & WigWag runtime

### BEGIN INIT INFO
# Provides:             devicejs
# Required-Start:       $remote_fs $time
# Required-Stop:        $remote_fs $time
# Should-Start:         $network $devicedbd
# Should-Stop:          $network $devicedbd
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    System logger
### END INIT INFO

# Source function library.
. /etc/init.d/functions

DEVICEJS_DIR="/wigwag/devicejs"
DEVJS_START_CMD="./bin/devjs --start -i wigwag -b -c conf/wigwag.conf.json"
DEVJS_STOP_CMD="./bin/devjs --shutdown -i wigwag"

DEVICEJS_LOG="/wigwag/log/devicejs.log"

function congig_cpu_scaling() {
   MAX_FREQ=/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
   MIN_FREQ=/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
   cat $MAX_FREQ > $MIN_FREQ
   MAX_FREQ=/sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
   MIN_FREQ=/sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
   cat $MAX_FREQ > $MIN_FREQ
}

function stop_devjs() {
    pushd $DEVICEJS_DIR
    $DEVJS_STOP_CMD > $DEVICEJS_LOG 2>&1 &
    popd
}
function run_devjs() {
    if [ -e $DEVICEJS_LOG ]; then
	# some trivial log rotation
	mv $DEVICEJS_LOG $DEVICEJS_LOG.1
    fi
    
    pushd $DEVICEJS_DIR
    $DEVJS_START_CMD > $DEVICEJS_LOG 2>&1 &
    popd
}

case "$1" in
    start)
	stop_devjs
	eval $COLOR_BOLD
	echo "Starting DeviceJS services."
	eval $COLOR_NORMAL
        congig_cpu_scaling
	run_devjs
	;;
    stop)
	echo "Stopping DeviceJS"
        stop_devjs
        ;;
    restart) 
	echo "Restarting DeviceJS"
	stop_devjs
        congig_cpu_scaling
	run_devjs
  	;;
      *)
	log_success_msg "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0

     
