#!/bin/bash

# Copyright (c) 2018, Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# /etc/init.d/devjsmon: Monitors DeviceJS

### BEGIN INIT INFO
# Provides:             devjsmon
# Required-Start:       $remote_fs $time
# Required-Stop:        $remote_fs $time
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        5
# Default-Stop:         0 1 6
# Short-Description:    DeviceJSMonitor
### END INIT INFO
WIGWAGROOT="/wigwag"
DEVJSMON_DIR="${WIGWAGROOT}/devicejs"
DEVJSMON_START_CMD="node ${WIGWAGROOT}/devicejs/core/exec/devjsmon.js"

DEVICEJSMON_LOG="${WIGWAGROOT}/log/devjsmon.log"

function stop_devjs() {
    pushd $DEVICEJS_DIR
    $DEVJS_STOP_CMD > $DEVICEJS_LOG 2>&1 &
    popd
}
function run_devjsmon() {
    if [ -e $DEVICEJSMON_LOG ]; then
	# some trivial log rotation
	mv $DEVICEJSMON_LOG $DEVICEJSMON_LOG.1
    fi
    
    pushd $DEVJSMON_DIR
    $DEVJSMON_START_CMD > $DEVICEJSMON_LOG 2>&1 &
    popd
}

case "$1" in
    start)
	eval $COLOR_BOLD
	echo "Starting DeviceJS Monitoring Services."
	eval $COLOR_NORMAL
	run_devjsmon
	;;
    stop)
	echo "Stopping DeviceJS Monitor Services"
        stop_devjsmon
        ;;
    restart) 
	echo "Restarting DeviceJS Monitor Services"
	stop_devjsmon
	run_devjsmon
  	;;
      *)
	echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
