#! /bin/sh

# Copyright (c) 2018, Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# /etc/init.d/emailIP: emails the IP address of WIgWag Relay

### BEGIN INIT INFO
# Provides:             emailIP
# Required-Start:       $remote_fs $time
# Required-Stop:        $remote_fs $time
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    System logger
### END INIT INFO

# Source function library.
. /etc/init.d/functions


EMAIL_SCRIPT="/wigwag/wwrelay-utils/dev-tools/bin/script-emailer-actual.py"

case "$1" in
    start)
	eval $COLOR_BOLD
	echo "Emailing IP address."
	eval $COLOR_NORMAL
	$EMAIL_SCRIPT
	;;
esac

