#! /bin/sh
# /etc/init.d/emailIP: emails the IP address of WIgWag Relay

### BEGIN INIT INFO
# Provides:             emailIP
# Required-Start:       $remote_fs $time
# Required-Stop:        $remote_fs $time
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    System logger
### END INIT INFO

# Source function library.
. /etc/init.d/functions


EMAIL_SCRIPT="/wigwag/wwrelay-utils/dev-tools/bin/script-emailer-actual.py"

case "$1" in
    start)
	eval $COLOR_BOLD
	echo "Emailing IP address."
	eval $COLOR_NORMAL
	$EMAIL_SCRIPT
	;;
esac

