#!/bin/bash

# Copyright (c) 2018, Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# /etc/init.d/devicedbd: starts WigWag Device Database

### BEGIN INIT INFO
# Provides:             devicedbd
# Required-Start:       $remote_fs $time
# Required-Stop:        $remote_fs $time
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        4 5
# Default-Stop:         0 1 6
# Short-Description:    Device Database for WigWag
### END INIT INFO

WIGWAGROOT="/wigwag"
RELAY_UPDATER_DIR="/updater/relay-updater"
RELAY_UPDATER_CMD="./bin/runUpdater.sh"
RELAY_UPDATER_LOG="${WIGWAGROOT}/log/relay-updater.log"

function run_relay_updater() {
    pushd $RELAY_UPDATER_DIR
    $RELAY_UPDATER_CMD > $RELAY_UPDATER_LOG 2>&1 &
    popd
}

case "$1" in
    start)
	eval $COLOR_BOLD
	echo "Starting Relay Updater Services."
	eval $COLOR_NORMAL
	run_relay_updater
	;;
    stop)
	echo "Stopping Relay Updater Services"
	killall -g runUpdater.sh 
	;;
    restart) 
	killall -g runUpdater.sh 
	run_relay_updater
  	;;
      *)
	echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0

     
