#! /bin/sh
# /etc/init.d/wwrelay: initialized the WigWag

### BEGIN INIT INFO
# Provides:             wwrelay
# Required-Start:       $remote_fs $time
# Required-Stop:        $remote_fs $time
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    System logger
### END INIT INFO

# Source function library.
. /etc/init.d/functions

WIGWAGROOT="/userdata/ww"
GPIO_DIR="${WIGWAGROOT}/wwrelay-utils/GPIO"
WWRELAY_LOG="${WIGWAGROOT}/log/wwrelay.log"
GPIO_LOG="${WIGWAGROOT}/log/gpio.log"


case "$1" in
    start)
	echo "Starting WigWag Relay"
        if [ -x $WWRELAY_LOG ] ; then
            mv $WWRELAY_LOG $WWRLAY_LOG.1
        fi

        if [ -x $GPIO_LOG ] ; then
            mv $GPIO_LOG $GPIO_LOG.1
        fi

        cd ${WIGWAGROOT}/wwrelay-utils/I2C
        /usr/bin/node ./ww_eeprom_reader.js  > $WWRELAY_LOG 2>&1
        /usr/bin/node ./enableRTC_charging.js >> $WWRELAY_LOG 2>&1
    	#$GPIO_DIR/setup-gpio.sh > $GPIO_LOG 2>&1
        cd ${WIGWAGROOT}/wwrelay-utils/GPIO/
        /usr/bin/node ./setup-gpio.js >> $WWRELAY_LOG 2>&1        
        cd ${WIGWAGROOT}/wwrelay-utils/slip-radio
        /usr/bin/node ./wwslip-embedmac.js embedMAC ${WIGWAGROOT}/devicejs/core/utils/node-6lbr/slip-radio_bin/slip-radio_econotag_B115200.bin slip-conf.json ${WIGWAGROOT}/devicejs/conf/wigwag.conf.json

	;;	
    stop)
	echo "Stopping WigWag Relay"
esac

exit 0

     
