#! /bin/sh
# /etc/init.d/wwrelay: initialized the WigWag

### BEGIN INIT INFO
# Provides:             wwrelay
# Required-Start:       $remote_fs $time
# Required-Stop:        $remote_fs $time
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    System logger
### END INIT INFO

# Source function library.
. /etc/init.d/functions

GPIO_DIR="/wigwag/wwrelay-utils/GPIO"

case "$1" in
    start)
	echo "Starting WigWag Relay"
    	$GPIO_DIR/setup-gpio.sh
	;;	
    stop)
	echo "Stopping WigWag Relay"
GPIO
esac

exit 0

     
