#!/bin/bash
# /etc/init.d/devicedbd: starts WigWag Device Database

### BEGIN INIT INFO
# Provides:             devicedbd
# Required-Start:       $remote_fs $time
# Required-Stop:        $remote_fs $time
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        4 5
# Default-Stop:         0 1 6
# Short-Description:    Device Database for WigWag
### END INIT INFO

WIGWAGROOT="/wigwag"
DEVICEDB_CMD="./run-devicedb.sh"

function run_devicedb() {
    $DEVICEDB_CMD &
}

case "$1" in
    start)
    eval $COLOR_BOLD
    echo "Starting DeviceDB services."
    eval $COLOR_NORMAL
    run_devicedb
    ;;
    stop)
    echo "Stopping DeviceDB"
    killall devicedb
    ;;
    restart) 
    killall devicedb
    run_devicedb
    ;;
      *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0

     
