#!/bin/bash

# Copyright (c) 2018, Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# /etc/init.d/devjssupport: Monitors Support App

### BEGIN INIT INFO
# Provides:             devjsssuport
# Required-Start:       $remote_fs $time
# Required-Stop:        $remote_fs $time
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        5
# Default-Stop:         0 1 6
# Short-Description:    DeviceJSApp
### END INIT INFO
export WIGWAGROOT="/wigwag"
DEVJSSUPPORT_DIR="${WIGWAGROOT}/support"
DEVJSSUPPORT_START_CMD="${WIGWAGROOT}/support/initialize.sh"

DEVICEJSSUPPORT_LOG="${WIGWAGROOT}/log/devjssupport.log"

function stop_devjssupport() {
    pushd $DEVJSSUPPORT_DIR
    $DEVJS_STOP_CMD > $DEVICEJSSUPPORT_LOG 2>&1 &
    popd
}
function run_devjssupport() {
    if [ -e $DEVICEJSSUPPORT_LOG ]; then
	# some trivial log rotation
	mv $DEVICEJSSUPPORT_LOG $DEVICEJSSUPPORT_LOG.1
    fi
    
    pushd $DEVJSSUPPORT_DIR
    $DEVJSSUPPORT_START_CMD > $DEVICEJSSUPPORT_LOG 2>&1 &
    popd
}

case "$1" in
    start)
	eval $COLOR_BOLD
	echo "Starting DeviceJS Support Services."
	eval $COLOR_NORMAL
	run_devjssupport
	;;
    stop)
	echo "Stopping DeviceJS Support Services"
        stop_devjssupport
        ;;
    restart) 
	echo "Restarting DeviceJS Support Services"
	stop_devjssupport
	run_devjssupport
  	;;
      *)
	echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
