#!/bin/bash

# Copyright (c) 2018, Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# /etc/init.d/devicejs: starts Arm edge-core
### BEGIN INIT INFO
# Provides:             edge-core
# Required-Start:       $remote_fs $time wwrelay
# Required-Stop:        $remote_fs $time
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        5
# Default-Stop:         0 1 6
# Short-Description:    System logger
### END INIT INFO
start_edge() {
    if [ ! -d "/userdata/mbed" ]; then
	# this directory is used to hold the developer certificate, if the user wants to use one
	echo "Creating /userdata/mbed"
	mkdir -p /userdata/mbed
	chown developer -R /userdata/mbed
    fi 
    cd /userdata/mbed
    /wigwag/mbed/edge-core/build/bin/edge-core  --http-port 9101  >> /wigwag/log/edge-core 2>&1 &
#    /wigwag/mbed/edge-core/build/mcc-linux-x86/existing/bin/edge-core --pt-api-port 9100 --http-port 9101 > /var/log/edge-core 2>&1 &
}
case "$1" in
	start)
		#
		echo "Starting mbed edge-core"
		start_edge
		;;
     #                                                                                                                                                                  
     stop)
		#
		echo "Stopping edge-core"
		killall edge-core
		;;
	#
	restart)
		#
		echo "Restarting edge-core"
		;;
	#
	*)
		#
		echo "Usage: \$0 {start|stop|restart}"
		exit 1
	#
esac
	exit 0

